# NO LONGER USED

validate = {
    "min_size": 500000, # 0.5 mega-pixel
    "min_width": 500,
    "min_height": 500,

    "max_blur": 0.1,
    "min_dynamic_range": 20,

    "max_faces": 1,
    "min_face_size": 200,
    "min_face_confidence": 0.6,
}

caption = ['clear', 'concept', 'wdtagger', 'promptgen'] # possible: 'clear', 'concept', 'wdtagger', 'promptgen', 'blip', 'wd14'

samples = [
    {
        "__version": 0,
        "enabled": False,
        "prompt": "",
        "negative_prompt": "",
        "height": 1024,
        "width": 1024,
        "seed": 42,
        "random_seed": True,
        "diffusion_steps": 20,
        "cfg_scale": 5.0,
        "noise_scheduler": "UniPC"
    }
]

concepts = [
    {
        "__version": 1,
        "image": {
            "__version": 0,
            "enable_crop_jitter": True,
            "enable_random_flip": True,
            "enable_fixed_flip": False,
            "enable_random_rotate": False,
            "enable_fixed_rotate": False,
            "random_rotate_max_angle": 0.0,
            "enable_random_brightness": False,
            "enable_fixed_brightness": False,
            "random_brightness_max_strength": 0.0,
            "enable_random_contrast": False,
            "enable_fixed_contrast": False,
            "random_contrast_max_strength": 0.0,
            "enable_random_saturation": False,
            "enable_fixed_saturation": False,
            "random_saturation_max_strength": 0.0,
            "enable_random_hue": False,
            "enable_fixed_hue": False,
            "random_hue_max_strength": 0.0,
            "enable_resolution_override": False,
            "resolution_override": "1024"
        },
        "text": {
            "__version": 0,
            "prompt_source": "sample",
            "prompt_path": "/tmp/lora/dataset",
            "enable_tag_shuffling": False,
            "tag_delimiter": ",",
            "keep_tags_count": 1
        },
        "name": "alla",
        "path": "/tmp/lora/dataset",
        "seed": -370590617,
        "enabled": True,
        "include_subdirectories": False,
        "image_variations": 1,
        "text_variations": 1,
        "balancing": 1.0,
        "balancing_strategy": "REPEATS",
        "loss_weight": 1.0
    }
]

config = {
    "__version": 3,
    "training_method": "LORA",
    "model_type": "STABLE_DIFFUSION_XL_10_BASE",
    "debug_mode": False,
    "debug_dir": "/tmp/onetrainer-debug",
    "workspace_dir": "/tmp/onetrainer-workspace",
    "cache_dir": "/tmp/onetrainer-cache",
    "tensorboard": False,
    "tensorboard_expose": False,
    "continue_last_backup": False,
    "include_train_config": "NONE",
    "base_model_name": "",
    "weight_dtype": "FLOAT_16",
    "output_dtype": "FLOAT_16",
    "output_model_format": "SAFETENSORS",
    "output_model_destination": "/tmp/lora/alla.safetensors",
    "gradient_checkpointing": True,
    "force_circular_padding": False,
    "concept_file_name": "/tmp/lora/concepts.json",
    "concepts": None,
    "circular_mask_generation": False,
    "random_rotate_and_crop": False,
    "aspect_ratio_bucketing": True,
    "latent_caching": True,
    "clear_cache_before_training": True,
    "learning_rate_scheduler": "COSINE",
    "learning_rate": 1,
    "learning_rate_warmup_steps": 200,
    "learning_rate_cycles": 1,
    "epochs": 100,
    "batch_size": 1,
    "gradient_accumulation_steps": 1,
    "ema": "OFF",
    "ema_decay": 0.999,
    "ema_update_step_interval": 5,
    "dataloader_threads": 2,
    "train_device": "cuda",
    "temp_device": "cpu",
    "train_dtype": "FLOAT_16",
    "fallback_train_dtype": "FLOAT_32",
    "enable_autocast_cache": True,
    "only_cache": False,
    "resolution": "1024",
    "attention_mechanism": "SDP",
    "align_prop": False,
    "align_prop_probability": 0.1,
    "align_prop_loss": "AESTHETIC",
    "align_prop_weight": 0.01,
    "align_prop_steps": 20,
    "align_prop_truncate_steps": 0.5,
    "align_prop_cfg_scale": 7.0,
    "mse_strength": 1.0,
    "mae_strength": 0.0,
    "vb_loss_strength": 1.0,
    "loss_weight_fn": "CONSTANT",
    "loss_weight_strength": 5.0,
    "dropout_probability": 0.0,
    "loss_scaler": "NONE",
    "learning_rate_scaler": "NONE",
    "offset_noise_weight": 0.0,
    "perturbation_noise_weight": 0.0,
    "rescale_noise_scheduler_to_zero_terminal_snr": False,
    "force_v_prediction": False,
    "force_epsilon_prediction": False,
    "min_noising_strength": 0.0,
    "max_noising_strength": 1.0,
    "noising_weight": 0.0,
    "noising_bias": 0.5,
    "unet": {
        "__version": 0,
        "model_name": "",
        "train": True,
        "stop_training_after": 0,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "prior": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": 0,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "text_encoder": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": 0,
        "stop_training_after_unit": "EPOCH",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "text_encoder_layer_skip": 0,
    "text_encoder_2": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": 0,
        "stop_training_after_unit": "EPOCH",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "text_encoder_2_layer_skip": 0,
    "vae": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "FLOAT_32"
    },
    "effnet_encoder": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "decoder": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "decoder_text_encoder": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "decoder_vqgan": {
        "__version": 0,
        "model_name": "",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "learning_rate": None,
        "weight_dtype": "NONE"
    },
    "masked_training": False,
    "unmasked_probability": 0.1,
    "unmasked_weight": 0.1,
    "normalize_masked_area_loss": False,
    "embedding_learning_rate": None,
    "preserve_embedding_norm": False,
    "embedding": {
        "__version": 0,
        "uuid": "73e030ab-1694-492a-a90e-5fb0cd62b4a7",
        "model_name": "",
        "placeholder": "<embedding>",
        "train": False,
        "stop_training_after": None,
        "stop_training_after_unit": "NEVER",
        "token_count": 1,
        "initial_embedding_text": "*"
    },
    "additional_embeddings": [],
    "embedding_weight_dtype": "FLOAT_16",
    "lora_model_name": "",
    "lora_rank": 32,
    "lora_alpha": 16.0,
    "lora_weight_dtype": "FLOAT_32",
    "optimizer": {
        "__version": 0,
        "optimizer": "PRODIGY",
        "adam_w_mode": False,
        "alpha": None,
        "amsgrad": False,
        "beta1": None,
        "beta2": None,
        "beta3": None,
        "bias_correction": False,
        "block_wise": False,
        "capturable": False,
        "centered": False,
        "clip_threshold": None,
        "d0": None,
        "d_coef": None,
        "dampening": None,
        "decay_rate": None,
        "decouple": False,
        "differentiable": False,
        "eps": None,
        "eps2": None,
        "foreach": False,
        "fsdp_in_use": False,
        "fused": False,
        "fused_back_pass": False,
        "growth_rate": None,
        "initial_accumulator_value": None,
        "is_paged": False,
        "log_every": None,
        "lr_decay": None,
        "max_unorm": None,
        "maximize": False,
        "min_8bit_size": None,
        "momentum": None,
        "nesterov": False,
        "no_prox": False,
        "optim_bits": None,
        "percentile_clipping": None,
        "r": None,
        "relative_step": False,
        "safeguard_warmup": False,
        "scale_parameter": False,
        "stochastic_rounding": True,
        "use_bias_correction": False,
        "use_triton": False,
        "warmup_init": False,
        "weight_decay": None,
        "weight_lr_power": None
    },
    "optimizer_defaults": {},
    "sample_definition_file_name": "/tmp/lora/samples.json",
    "samples": None,
    "sample_after": 0,
    "sample_after_unit": "NEVER",
    "sample_image_format": "JPG",
    "samples_to_tensorboard": True,
    "non_ema_sampling": True,
    "backup_after": 0,
    "backup_after_unit": "NEVER",
    "rolling_backup": False,
    "rolling_backup_count": 0,
    "backup_before_save": False,
    "save_after": 0,
    "save_after_unit": "NEVER",
    "save_filename_prefix": ""
}
